<a href="https://colab.research.google.com/github/subhiksha9/cs_lab/blob/main/Factor_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df=pd.read_excel("/content/data.xlsx")
df

f  m  bf
0   3  6   5
1   7  3   3
2  10  9   8
3   3  9   7
4  10  6   5

In [6]:
import statistics as st
import numpy as np
import math
mean=[]
sd=[]
for i in df:
  mean.append(st.mean(df[i]))
  sd.append(round(st.stdev(df[i]),2))
count=0
#print(sd)
a=np.array([df["f"],df["m"],df["bf"]],dtype=float)
rows,cols=a.shape
for i in range(rows):
  for j in range(cols):
    a[i][j]=(a[i][j]-mean[count])/sd[count]
  count+=1
a=np.transpose(a)
#print(a)
c=np.dot(np.transpose(a),a)/len(a)
print(c)

[[ 0.79869482 -0.04086219  0.06428519]
 [-0.04086219  0.7999873   0.78455409]
 [ 0.06428519  0.78455409  0.79947403]]


In [7]:
values,vectors=np.linalg.eig(c)
vectors=np.transpose(vectors)
values=list(values)
values_desc=[]
values_desc=sorted(values)
values_desc=values_desc[::-1]
#print(values)
#print(vectors)
sum=0
component=[]
tot_sum=0
req_range=90
final=[]
for i in values_desc:
  tot_sum+=i
compo=[]
for i in values_desc:
  sum+=i
  component=(sum/tot_sum)*100
  compo.append([component,i])
#print(pd.DataFrame(compo))
new_vec=[]
for i in vectors:
  count_neg=0
  for j in i:
    if j<0:
      count_neg+=1
  if(count_neg>1):
    i=(-1)*i
    new_vec.append(i)
  else:
    new_vec.append(i)
vectors=new_vec
iter=1
final=[]
iter=1
final=[]
print(vectors)

[array([ 0.09366385,  0.70318717, -0.7048084 ]), array([ 0.99537924, -0.08117643,  0.05128887]), array([0.02114816, 0.70635557, 0.70754121])]


In [8]:
i=1
for j in compo:
  if j[0]<=req_range:
    i+=1
factors=[]
iter=1
sum=0
for j in compo:
  if(iter<=i):
    ind=values.index(j[1])
    vec=vectors[ind]
    factor=list(np.dot(math.sqrt(values[ind]),vec))
    sum+=values[ind]
    factors.append(factor)
  iter+=1
h2=[]
for i in range(len(factors[0])):
  new=0
  for j in range(len(factors)):
    new=new+(factors[j][i])**2
  h2.append(new)
percentage=[(values[2]/sum)*100,(values[1]/sum)*100]
table={"heading":["finance","marketing","buisness","variance explained","%of variance"],"f1":[factors[0][0],factors[0][1],factors[0][2],values[2],percentage[0]],"f2":[factors[1][0],factors[1][1],factors[1][2],values[1],percentage[1]],"h2":[h2[0],h2[1],h2[2],sum,sum]}
req_table=pd.DataFrame(table)
print(req_table)

              heading         f1         f2        h2
0             finance   0.026622   0.893260  0.798623
1           marketing   0.889177  -0.072848  0.795942
2            buisness   0.890669   0.046027  0.795410
3  variance explained   1.584635   0.805340  2.389975
4        %of variance  66.303420  33.696580  2.389975


In [9]:
#transformation matrix
f1=[factors[0][0],factors[0][1],factors[0][2]]
f2=[factors[1][0],factors[1][1],factors[1][2]]
deg=math.radians(2)
f1s=[]
t=np.array([[math.cos(deg),(-1)*math.sin(deg)],[math.sin(deg),math.cos(deg)]])
for i in range(len(f1)):
  f1[i]=(f1[i]*math.cos(deg))+(f2[i]*math.sin(deg))
  f2[i]=(f2[i]*math.cos(deg))-(f1[i]*math.sin(deg))
h2s=[]
for i in range(len(f1)):
  h2s.append((f1[i]**2)+(f2[i]**2))
table={"variable":["finance","marketing","buisness","variance","% of variance"],"f1*":[f1[0],f1[1],f1[2],values[2],percentage[0]],"f2*":[f2[0],f2[1],f2[2],values[1],percentage[1]],"h2":[h2s[0],h2s[1],h2s[2],sum,sum]}
loadings=pd.DataFrame(table)
print(loadings)

        variable        f1*        f2*        h2
0        finance   0.057780   0.890700  0.796685
1      marketing   0.886092  -0.103728  0.795919
2       buisness   0.891733   0.014878  0.795409
3       variance   1.584635   0.805340  2.389975
4  % of variance  66.303420  33.696580  2.389975


In [10]:
#inference
for i in range(len(f1)):
  if(f1[i]>f2[i]):
    print(i+1,"th variable in first group")
  else:
    print(i+1,"th variable in second group")

1 th variable in second group
2 th variable in first group
3 th variable in first group
