<a href="https://colab.research.google.com/github/subhiksha9/cs_lab/blob/main/multiple_regression_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#transpose
def transpose(arr):
  t=[]
  for i in range(len(arr[0])):
    T=[]
    for j in range(len(arr)):
      T.append(arr[j][i])
    t.append(T)
  return t

In [2]:
#multipliction
def mul(a,b):
  c=[]
  n=len(a)
  m=len(a[0])
  q=len(b[0])
  for i in range(n):
    C=[]
    for j in range(q):
      multi=0
      for k in range(m):
        multi=multi+a[i][k]*b[k][j]
      C.append(round(multi,4))
    c.append(C)
  return c

In [3]:
#inverse
def inverse(a):
  n=len(a)
  m=len(a[0])
  cofactor=[]
  det=0
  if n==2 and m==2:
    cofactor.append([a[1][1],-1*a[0][1]])
    cofactor.append(-1*[a[1][0],a[0][0]])
    det=cofactor[0][0]*cofactor[1][1]-cofactor[0][1]*cofactor[1][0]
  else:
    for i in range(n):
      co=[]
      for j in range(m):
        c=[]
        for k in range(n):
          for o in range(m):
            if i!=k and j!=o:
              c.append(a[k][o])
        if (i+j)%2!=0:
          q=-1*(c[0]*c[3]-c[1]*c[2])
        else:
          q=(c[0]*c[3]-c[1]*c[2])
        co.append(q)
        if i==0:
          det=det+a[i][j]*q
      cofactor.append(co)
    inv=transpose(cofactor)
  ine=inv/det
  return ine

In [4]:
#importing libraries
import numpy as np
import pandas as pd
import scipy.stats as s

In [6]:
#inputs
df=pd.read_excel("/content/data.xlsx")
print(df)

      y  x1  x2  x3
0   100   1   9  62
1   110   1   8  58
2   105   1   7  64
3    94   1  14  60
4    95   1  12  63
5    99   1  10  57
6   104   1   7  55
7   108   1   4  56
8   105   1   6  59
9    98   1   5  61
10  105   1   7  57
11  110   1   6  60


In [7]:
x1=df['x1']
x2=df['x2']
x3=df['x3']
y=df['y']
print(x1)
print(x2)
print(x3)
print(y)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
Name: x1, dtype: int64
0      9
1      8
2      7
3     14
4     12
5     10
6      7
7      4
8      6
9      5
10     7
11     6
Name: x2, dtype: int64
0     62
1     58
2     64
3     60
4     63
5     57
6     55
7     56
8     59
9     61
10    57
11    60
Name: x3, dtype: int64
0     100
1     110
2     105
3      94
4      95
5      99
6     104
7     108
8     105
9      98
10    105
11    110
Name: y, dtype: int64


In [8]:
arr1=x1.to_numpy()
arr2=x2.to_numpy()
arrx=x3.to_numpy()
arr3=y.to_numpy()
print(arr1,arr2,arr3,arrx)

[1 1 1 1 1 1 1 1 1 1 1 1] [ 9  8  7 14 12 10  7  4  6  5  7  6] [100 110 105  94  95  99 104 108 105  98 105 110] [62 58 64 60 63 57 55 56 59 61 57 60]


In [9]:
arr=np.array([arr1,arr2,arrx])
print(arr)
y_arr=np.array([arr3])
print(y_arr)

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 9  8  7 14 12 10  7  4  6  5  7  6]
 [62 58 64 60 63 57 55 56 59 61 57 60]]
[[100 110 105  94  95  99 104 108 105  98 105 110]]


In [10]:
X=transpose(arr)
print(X)
Y=transpose(y_arr)
print(Y)

[[1, 9, 62], [1, 8, 58], [1, 7, 64], [1, 14, 60], [1, 12, 63], [1, 10, 57], [1, 7, 55], [1, 4, 56], [1, 6, 59], [1, 5, 61], [1, 7, 57], [1, 6, 60]]
[[100], [110], [105], [94], [95], [99], [104], [108], [105], [98], [105], [110]]


In [11]:
def display(m):
    for i in range(len(m)):
        for j in range(len(m[0])):
            print(m[i][j],end=" ")
        print()

In [12]:
Xtx=mul(arr,X)
display(Xtx)

12 95 712 
95 845 5663 
712 5663 42334 


In [14]:
q=mul(arr,Y)
display(q)

1233 
9636 
73094 


In [15]:
inv=inverse(Xtx)
display(inv)

40.89440259768947 0.11404651984714276 -0.7030438912327981 
0.11404651984714276 0.011751452364648451 -0.003490092995515893 
-0.7030438912327981 -0.003490092995515893 0.012314726867089306 


In [16]:
betacap=mul(inv,q)
display(betacap)

133.4605 
-1.2485 
-0.351 


In [17]:
b=np.ravel(betacap)
print(b)

[133.4605  -1.2485  -0.351 ]


In [18]:
print("equation is:","y=",betacap[0][0],"+",betacap[1][0],"x1",betacap[2][0],"x2")

equation is: y= 133.4605 + -1.2485 x1 -0.351 x2


In [19]:
yexp=y
ycal=betacap[0][0]+(betacap[1][0]*x2)+(betacap[2][0]*x3)
print(ycal)

0     100.4620
1     103.1145
2     102.2570
3      94.9215
4      96.3655
5     100.9685
6     105.4160
7     108.8105
8     105.2605
9     105.8070
10    104.7140
11    104.9095
dtype: float64


In [21]:
error=yexp-ycal
print(error)

0    -0.4620
1     6.8855
2     2.7430
3    -0.9215
4    -1.3655
5    -1.9685
6    -1.4160
7    -0.8105
8    -0.2605
9    -7.8070
10    0.2860
11    5.0905
dtype: float64


In [22]:
def sum(x):
    s=0
    for i in x:
        s=s+i
    return s

In [23]:
errorsq=error*error
sum_error=sum(errorsq)
print("sse:",sum_error)

sse: 151.4104097499999


In [24]:
ysum=sum(y)
ymean=ysum/len(y)
print(ymean)

102.75


In [25]:
ydiff=y-ymean
ydif=ydiff**2
sst=sum(ydif)
print("sst:",sst)

sst: 330.25


In [26]:
ssr=sst-sum_error
print("ssr:",ssr)

ssr: 178.8395902500001


In [27]:
coff_of_det=ssr/sst
print(coff_of_det)

0.5415279038607119


In [28]:
if(coff_of_det>0.90):
    print("good fit")
else:
    print("bad fit")

bad fit


Anova

In [29]:
df_regression=len(betacap)-1
df_error=len(df)-len(betacap)
mean_ssr=ssr/df_regression
mean_sse=sum_error/df_error
Fcal=mean_ssr/mean_sse
print("Fcal:",Fcal)

Fcal: 5.315210212123484


In [30]:
Ftab=s.f.ppf(.95,df_regression,df_error)
print("tablevalue:",Ftab)

tablevalue: 4.25649472909375


In [31]:
if(Fcal>=Ftab):
    print("reject null hypothesis and accept model")
else:
    print("accept null and reject model")

reject null hypothesis and accept model


test for parameters

In [32]:
c=[]
for i in range(len(inv)):
    for j in range(len(inv[0])):
        if(i==j):
            c.append(inv[i][j])
print(c)

[40.89440259768947, 0.011751452364648451, 0.012314726867089306]


In [33]:
se=[]
t=[]
for i in c:
    p=(mean_sse*i)**0.5
    se.append(p)
for i in range(len(se)):
    s=b[i]/se[i]
    t.append(abs(s))
print(t)

[5.088200318385074, 2.8079292558137747, 0.7711486663819923]


In [35]:
import scipy.stats
ttab=scipy.stats.t.ppf(0.05/2,df_error)
t_tab=abs(ttab)
print(t_tab)

2.262157162740992


In [36]:
for i in t:
    if(i>=t_tab):
        print("reject null and variable is contributing to model")
    else:
        print("accept null and variable is not contributing to model")

reject null and variable is contributing to model
reject null and variable is contributing to model
accept null and variable is not contributing to model
