<a href="https://colab.research.google.com/github/subhiksha9/cs_lab/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
threshold=95
x1=[90,90,60,60,30]
x2=[60,90,60,60,30]
x3=[90,30,60,90,30]
x=[]
cp=[]

In [14]:
#to store cumulative proportion values
for i in range(len(x1)):
    x.append([x1[i],x2[i],x3[i]])
mu=[0 for i in range(len(x))]

In [15]:
#calculation of mu i.e mean
for i in range(len(x1)):
    mu[0]+=x[i][0]
    mu[1]+=x[i][1]
    mu[2]+=x[i][2]
mu[0]=mu[0]/len(x)
mu[1]=mu[1]/len(x)
mu[2]=mu[2]/len(x)
import numpy as np

In [16]:
#calculation of x-mu
for i in range(len(x)):
    x[i][0]=x[i][0]-mu[0]
    x[i][1]=x[i][1]-mu[1]
    x[i][2]=x[i][2]-mu[2]

In [17]:
#calculation of variance covariance matrix
def mul(x,y):
    res =  [[0 for i in range(len(y[0]))] for j in range(len(x))]
    for i in range(len(x)):
        for j in range(len(y[0])):
            for k in range(len(y)):
                res[i][j]+=x[i][k]*y[k][j]
    return res
def transpose(x):
    xt=[[0 for i in range(len(x))] for j in range(len(x[0]))]
    for i in range(len(x)):
        for j in range(len(x[0])):
             xt[j][i]=x[i][j]
    return xt
def trace(x):
    s=0
    for i in range(len(x)):
        for j in range(len(x[0])):
            if i==j:
                s+=x[i][j]
    return s
def cofactor(m):
    cf=[[0 for i in range(len(m))] for j in range(len(m[0]))]
    for i in range(len(m)):
        for j in range(len(m[0])):
            cf[i][j]=((-1)**(i+j))*det(minor(m,i,j))
    return cf
def inv(m):
    inv=[[0 for i in range(len(m))] for j in range(len(m[0]))]
    cf=transpose(cofactor(m))
    for i in range(len(m)):
        for j in range(len(m[0])):
            inv[i][j]=cf[i][j]/det(m)
    return inv
def minor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]
def det(m):
    if len(m)==2:
        return (m[0][0]*m[1][1]-m[0][1]*m[1][0])
    else:
        d=0
        for c in range(len(m)):
            d+=((-1)**c)*m[0][c]*det(minor(m,0,c))
    return d
c=mul(transpose(x),x)
for i in range(len(c)):
    for j in range(len(c[0])):
        c[i][j]=c[i][j]/len(x)

In [18]:
#calculation of eigen values lambda values are e1,e2
if(len(c)==2):
    a=1
    b=-c[0][0]-c[1][1]
    d=(c[0][0]*c[1][1])-(c[0][1]*c[1][0])
    e1=(-b+(b**2-(4*a*d)))/(2*a)
    e2=(-b-(b**2-(4*a*d)))/(2*a)
    e=[e1,e2]
else:
    import numpy as np
    from numpy import linalg
    e,v=linalg.eig(c)
    e=np.array(e)
    v=np.array(v)
    idx=e.argsort()[::-1]
    e=e[idx]
    v=v[:,idx]
print("eigen vector of ",i,":",v)
for i in range(len(e)):
    cp.append((e[i]/sum(e))*100)
    if (e[i]/sum(e))*100 > threshold:
        break
red=len(cp)-1

print('reduced components:',v[:red])

eigen vector of  2 : [[-0.65580225 -0.3859988   0.6487899 ]
 [-0.4291978  -0.51636642 -0.74104991]
 [-0.62105769  0.7644414  -0.17296443]]
reduced components: [[-0.65580225 -0.3859988   0.6487899 ]
 [-0.4291978  -0.51636642 -0.74104991]]
